version: "3.7"

services:

  frontend:
    container_name: snapface-frontend
    build: ./snapface-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    container_name: snapface-backend
    build: ./snapface-backend
    ports:
      - "3000:3000"
